proverbs = {
    '1' : 'If you want to go fast, go alone. If you want to go far, go together. | African Proverb',
    '2' : 'Fall seven times, stand up eight. | Japanese Proverb',
    '3' : 'Shared joy is a double joy; shared sorrow is half a sorrow. | Swedish Proverb',
    '4' : 'Words should be weighed, not counted. | Yiddish Proverb',
    '5' : 'If you can’t live longer, live deeper. | Italian Proverb',
    '6' : 'Do good and throw it in the sea. | Arab Proverb',
    '7' : 'Where love reigns, the impossible may be attained. | Indian Proverb',
    '8' : 'It’s better to light a candle than curse the darkness. | Chinese Proverb',
    '9' : 'A man who uses force is afraid of reasoning. | Kenyan Proverb',
    '10' : 'Still waters run deep. | Latin Proverb',
    '11' : 'He who does not travel, does not know the value of men. | Moorish Proverb',
    '12' : 'The night rinses what the day has soaped. | Swiss Proverb',
    '13' : 'Measure a thousand times and cut once. | Turkish Proverb',
    '14' : 'A spoon does not know the taste of soup, nor a learned fool the taste of wisdom. | Welsh Proverb',
    '15' : 'The most beautiful fig may contain a worm. | Zulu Proverb',
    '16' : 'Change yourself and fortune will change. | Portuguese Proverb',
    '17' : 'In love, there is always one who kisses and one who offers the cheek. | French Proverb',
    '18' : 'Evil enters like a needle and spreads like an oak tree. | Ethiopian Proverb',
    '19' : 'Who begins too much accomplishes little. | German Proverb',
    '20' : 'Whoever gossips to you will gossip about you. | Spanish Proverb',
    '21' : 'Beauty lies in the eye of the beholder. | English Proverb',
    '22' : 'Don’t sail out farther than you can row back. | Danish Proverb',
    '23' : 'There is no shame in not knowing; the shame lies in not finding out. | Russian Proverb',
    '24' : 'Age is honorable and youth is noble. | Irish Proverb',
    '25' : 'In a battle between elephants, the ants get squashed. | Thai Proverb',
    '26' : 'If you take big paces, you leave big spaces. | Burmese Proverb',
    '27' : 'Before you score, you first must have a goal. | Greek Proverb',
    '28' : 'Good advice is often annoying, bad advice never is. | French Proverb',
    '29' : 'Give a man a fish, and you feed him for a day. Teach a man to fish, and you feed him for a lifetime. | Chinese Proverb',
    '30' : 'Do not rejoice at my grief, for when mine is old, yours will be new. | Spanish Proverb',
    '31' : 'What you see in yourself is what you see in the world. | Afghan Proverb',
    '32' : 'It takes a whole village to raise a child. | African Proverb',
    '33' : 'Examine what is said, not who speaks. | Arab Proverb',
    '34' : 'Two wrongs don’t make a right. | English Proverb',
    '35' : 'A large chair does not make a king. | Sudanese Proverb',
    '36' : 'Instruction in youth is like engraving in stone. | Moroccan Proverb',
    '37' : 'Deep doubts, deep wisdom; small doubts, small wisdom. | Chinese Proverb',
    '38' : 'A man does not seek his luck; luck seeks its man. | Turkish Proverb',
    '39' : 'A teacher is better than two books. | German Proverb',
    '40' : 'A beautiful thing is never perfect. | Egyptian Proverb',
    '41' : 'The reputation of a thousand years may be determined by the conduct of one hour. | Japanese Proverb',
    '42' : 'Character is always corrupted by prosperity. | Icelandic Proverb',
    '43' : 'A fault confessed is half redressed. | Zulu Proverb',
    '44' : 'To be willing is only half the task. | Armenian Proverb',
    '45' : 'Everyone is kneaded out of the same dough, but not baked in the same oven. | Yiddish Proverb',
    '46' : 'The heart that loves is always young. | Greek Proverb',
    '47' : 'He who always thinks it is too soon is sure to come too late. | German Proverb',
    '48' : 'Turn your face to the sun and the shadows will fall behind you. | New Zealander Proverb',
    '49' : 'When the sun rises, it rises for everyone. | Cuban Proverb',
    '50' : 'No man can paddle two canoes at the same time. | Bantu Proverb',
    '51' : 'If you go to a donkey’s house, don’t talk about ears. | Jamaican Proverb',
    '52' : 'Speak the truth, but leave immediately after. | Slovenian Proverb'
}